# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-13 01:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180313_0148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article_tag',
            new_name='Articletag',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 13, 1, 51, 2, 106535, tzinfo=utc)),
        ),
    ]
