# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-13 03:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180313_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='articel_tag',
            new_name='article_tag',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 13, 3, 37, 46, 587832, tzinfo=utc)),
        ),
    ]
