# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-09 07:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 7, 2, 54, 507466, tzinfo=utc)),
        ),
    ]
