# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-10 03:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180309_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 10, 3, 44, 53, 396498, tzinfo=utc)),
        ),
    ]
