# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-11 04:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180310_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 11, 4, 29, 8, 306889, tzinfo=utc)),
        ),
    ]
