# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-11 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180311_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 11, 12, 43, 54, 741324, tzinfo=utc)),
        ),
    ]
