# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-12 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180312_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 12, 12, 19, 16, 64194, tzinfo=utc)),
        ),
    ]
