# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-14 02:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180313_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 2, 18, 49, 49497, tzinfo=utc)),
        ),
    ]
